
import { StandardTableView } from "std-widgets.slint";
export component List inherits Rectangle {
    in-out property <[[StandardListViewItem]]> list;
    StandardTableView { 
        width: parent.width;
        height: parent.width*0.65;
        columns: [
            {title:"SongName"},
            {title:"Artist"},
            {title:"Album"},
            {title:"Year"},
            // {title:"Genre"},
        ];
        rows: root.list;
     }
}