import { StyleMetrics } from "std-widgets.slint";
import { Ctrl } from "page/ctrl.slint";
import { List } from "page/list.slint";
export component App inherits Window {
    width: 1240px;
    height: 760px;
    // icon: @image-url("reso/logo.png");
    background: StyleMetrics.window-background;
    title: @tr("Music_Player");
    callback loadfile <=> ct.loadfile;
    callback stop <=> ct.stop;
    callback paly <=> ct.play;
    callback next <=> ct.next;
    callback peaue <=> ct.peaue;
    in-out property list <=> list.list;
    VerticalLayout {
        alignment: start;
        spacing: 10px;
            ct := Ctrl {
                width: root.width;
                height: root.height*0.05;
            }
            list := List{
                width: root.width;
                height: root.height;
            }
        
    }
}